//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQ.QA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionInfo
    {
        public ActionInfo()
        {
            this.Role = new HashSet<Role>();
            this.R_User_ActionInfo = new HashSet<R_User_ActionInfo>();
        }
    
        public int ID { get; set; }
        public short DelFlag { get; set; }
        public int SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public string Url { get; set; }
        public string HttpMethod { get; set; }
        public string ActionName { get; set; }
        public string Remark { get; set; }
        public string Controoller { get; set; }
        public string ActionMethod { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
        public virtual ICollection<R_User_ActionInfo> R_User_ActionInfo { get; set; }
    }
}
