//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQ.QA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer1 : DbContext
    {
        public DataModelContainer1()
            : base("name=DataModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<ActionInfo> ActionInfo { get; set; }
        public DbSet<R_User_ActionInfo> R_User_ActionInfo { get; set; }
        public DbSet<UserInfoMeta> UserInfoMeta { get; set; }
        public DbSet<MenuInfo> MenuInfo { get; set; }
    }
}
