//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQ.QA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.UserInfo = new HashSet<UserInfo>();
        }
    
        public int ID { get; set; }
        public short DelFlag { get; set; }
        public int SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public int ParentId { get; set; }
        public string DepName { get; set; }
        public int DepMasterId { get; set; }
        public string DepNo { get; set; }
        public bool IsLeaf { get; set; }
        public int Level { get; set; }
        public string TreePath { get; set; }
    
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}
