//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQ.QA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuInfo
    {
        public int ID { get; set; }
        public string MenuName { get; set; }
        public short DelFlag { get; set; }
        public int SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public int ActionInfoId { get; set; }
        public string Remark { get; set; }
        public int Sort { get; set; }
        public bool IsVisable { get; set; }
        public int DialogHeight { get; set; }
        public int DialogWidth { get; set; }
        public string IconUrl { get; set; }
        public int ParentId { get; set; }
    }
}
