//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQ.QA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoMeta
    {
        public int ID { get; set; }
        public string QQ { get; set; }
        public string Msn { get; set; }
        public int UserInfoId { get; set; }
        public short DelFlag { get; set; }
        public int SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
    }
}
