//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQ.QA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_Instance
    {
        public WF_Instance()
        {
            this.WF_Step = new HashSet<WF_Step>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.DateTime OutTime { get; set; }
        public short State { get; set; }
        public short Result { get; set; }
        public string Content { get; set; }
        public int WF_TempID { get; set; }
        public short Level { get; set; }
        public int Field { get; set; }
        public System.Guid InstanceId { get; set; }
    
        public virtual WF_Temp WF_Temp { get; set; }
        public virtual ICollection<WF_Step> WF_Step { get; set; }
    }
}
