//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQ.QA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_Step
    {
        public int ID { get; set; }
        public System.TimeSpan SubTime { get; set; }
        public System.TimeSpan ProcessTime { get; set; }
        public int ProcessBy { get; set; }
        public string StepName { get; set; }
        public string Comment { get; set; }
        public string FlowTo { get; set; }
        public string IsStart { get; set; }
        public string IsEnd { get; set; }
        public string State { get; set; }
        public int WF_InstanceID { get; set; }
    
        public virtual WF_Instance WF_Instance { get; set; }
    }
}
