//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQ.QA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_Temp
    {
        public WF_Temp()
        {
            this.WF_Instance = new HashSet<WF_Instance>();
        }
    
        public int ID { get; set; }
        public string TempName { get; set; }
        public System.DateTime SubTime { get; set; }
        public string ActivityType { get; set; }
        public string Description { get; set; }
        public string FormTemp { get; set; }
        public short State { get; set; }
    
        public virtual ICollection<WF_Instance> WF_Instance { get; set; }
    }
}
